# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: exchange
appVersion: v1
replicaCount: 1

image:
  repository: ghcr.io/cisco-outshift-ai-agents/exchange-server
  tag: latest
  pullPolicy: Always
  pullSecret:

service:
  port: 8000

config:
  farmAgentHost: ""
  farmAgentPort: ""
  azureOpenAiEndpoint: ""
  azureOpenAiDeployment: ""
  azureOpenAiApiVersion: ""
  llmProvider: ""
  transportServerEndpoint: ""
  defaultMessageTransport: ""

# serviceaccount:
#   annotations:
#     eks.amazonaws.com/role-arn: REPLACE_WITH_ROLE_ARN


ingress:
  enabled: true
  name: exchange-ingress
  className: nginx
  host: exchange-ingress.outshift.io
  serviceName: exchange-ingress
  servicePort: 8000
  tlsSecret: exchange-ingress-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /

probes:
  livenessProbeEnabled: false
  readinessProbeEnabled: false
  port: 8000
  endpoint: /v1/health

resources:
  enabled: false
  limits:
    cpu: 2000m
    memory: 2500Mi
  requests:
    cpu: 200m
    memory: 500Mi
